# -*- coding: utf-8 -*-
"""UmDois2023.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10md5q8FTe0BXDXVTFtXe46VxE7MUgGx0
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
from google.colab import files

# Lista de links das rodadas
links = [
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-palpites-1-rodada-do-brasileirao-tabela-dicas-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-palpites-2-rodada-do-brasileirao-tabela-dicas-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-palpites-3-rodada-do-brasileirao-tabela-dicas-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-palpites-4-rodada-do-brasileirao-tabela-dicas-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-palpites-5-rodada-do-brasileirao-tabela-dicas-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-palpites-6-rodada-do-brasileirao-tabela-dicas-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-palpites-7-rodada-do-brasileirao-tabela-dicas-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-palpites-8-rodada-do-brasileirao-tabela-dicas-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-palpites-9-rodada-do-brasileirao-tabela-dicas-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-palpites-10-rodada-do-brasileirao-tabela-dicas-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-palpites-11-rodada-do-brasileirao-tabela-dicas-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-palpites-12-rodada-do-brasileirao-tabela-dicas-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-palpites-13-rodada-do-brasileirao-tabela-dicas-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-palpites-14-rodada-do-brasileirao-tabela-dicas-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-15a-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-16-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-17-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-18-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-19-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-20-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-21-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-22-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-23-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-24-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-25-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-26-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-27-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-28-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-29-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-30-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-31-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-32-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-33-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-34-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-35-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-36-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-37-rodada-do-brasileirao-2023/",
  "https://www.umdoisesportes.com.br/dicas-do-cartola/cartola-jogos-e-palpites-da-38-rodada-do-brasileirao-2023/"
]

# Lista para armazenar os dados extraídos
dados = []

# Função para extrair palpites de uma URL
def extrair_palpites(url, rodada):
    resposta = requests.get(url)
    if resposta.status_code != 200:
        print(f"Erro ao acessar {url}")
        return

    soup = BeautifulSoup(resposta.text, "html.parser")
    jogos = soup.find_all(text=re.compile(r'Placar: \d+x\d+'))

    for jogo in jogos:
        match = re.search(r"(\d{1,2}h[0-9]{0,2})?\s*-?\s*(.+?)\s*x\s*(.+?)\s*-\s*Placar:\s*(\d+)x(\d+)", jogo)
        if match:
            mandante = match.group(2).strip()
            visitante = match.group(3).strip()
            gols_mandante = int(match.group(4))
            gols_visitante = int(match.group(5))

            # Define o resultado baseado no placar
            if gols_mandante > gols_visitante:
                resultado = 1  # Vitória do mandante
            elif gols_mandante < gols_visitante:
                resultado = 2  # Vitória do visitante
            else:
                resultado = 0  # Empate

            # Adiciona os dados na lista
            dados.append([rodada, mandante, visitante, resultado])

# Percorre todas as URLs e extrai os dados
for i, link in enumerate(links, start=1):
    extrair_palpites(link, rodada=i)

# Criar DataFrame
df = pd.DataFrame(dados, columns=["Rodada", "Mandante", "Visitante", "Resultado"])

# Salvar em um arquivo Excel
arquivo_excel = "palpites_brasileirao.xlsx"
df.to_excel(arquivo_excel, index=False)

# Baixar o arquivo automaticamente
files.download(arquivo_excel)